### ISSUE TITLE
Motor arm roller  

### ISSUE THREAD

**Issue by Viproz** [Jfriesen222/GUS_CAD_Files#1]
In this file https://github.com/Jfriesen222/GUS_CAD_Files/blob/master/STL/MOTOR_ARM.STL we can see a roller made of plastic, I don't think it's intentional since in the assembly you have a roller at the same place.

**Comment by Jfriesen222** [comment]
Hey Viproz, those two plastic parts are actually intentional. Previously that was a roller, but both remain static during normal operation, so I replaced an extra pulley with a printed static roller. All three of my arms use this it works great!

**Comment by Jfriesen222** [comment]
But I should fix the assembly to reflect that

**Comment by Jfriesen222** [comment]
Ok I changed back to the previous design to prevent string wear so this is no longer part of the design. closing this issue.
